print("XpLevel. 2025 © All right reserved.")
print("XPL-C 2.0 Beta -2025WEDMAR12 - 2%")
print("for help about any objects or keyword type h[object or keyword]")
print("for more info type credits , lic or copyright")
ahj = input()
if (ahj == "h['InDisplay.show']"):
  print("")
  print("XpLevel Help Guilde InTerminal Comment line. for version 2.0 of Xple compiler.")
  print("")
  print("InDisplay.show is A function to print a message in display (terminal output)")
  print("Use : InDisplay.show[message]")
  print("example:")
  print("")
  print("ma_in[")
  print("    createMain")
  print("    InDisplay.show('')")
  print("    endMain")
  print("]")
  print("InDisplay.show['Hello World']")
  print("")
  print("at up example, we have a ma_in part this part of code just allow to use one fuction on. better you leave alone ma_in for type more code with a InDisplay.show with use '(' insted '[' and ')' insted ']'.")
  print("and we close ma_in with endMain and start it with createMain.")
  print("and type InDisplay.show and a varible with ['hi'].")
  print("after compile its will show hi.")
  print("")
  print("if first time you use XpLevel, for learn compelety go to http://xp.ct.ws/learn.html")
  exit()
else:
  if (ahj == "h['storio']"):
    print("")
    print("XpLevel Help Guilde InTerminal Comment line. for version 2.0 of Xple compiler.")
    print("")
    print("storio help gulide for version 2.0 of xplevel compiler.")
    print('')
    print("storio is a keyword for string manager. storio syntax is like this:")
    print("")
    print("storio [the-keyword-of-what-storio-do] thevarabilename = 'text'")
    print("")
    print("XpLevel has 2 keyword to do:")
    print("Instr >>> to select the var you wanna create is a string.")
    print("recall >>> return your var.")
    print("the recall is do this:")
    print("if you create a function to it answer be a textvmust use storio [recall] to do that.")
    print("")
    print("example of Instr:")
    print("")
    print("ma_in[")
    print("    createMain")
    print('    InDisplay.show("")')
    print("    endMain")
    print("]")
    print("storio [Instr] hi = 'hi again']")
    print("InDisplay.show[hi]")
    print("")
    print("example of recall:")
    print("")
    print("ma_in[")
    print("    createMain")
    print('    InDisplay.show("")')
    print("    endMain")
    print("]")
    print("createFn hi[] startCreation")
    print("  storio [Instr] ha = 'ha ha ha']")
    print("  storio [recall] ha")
    print("endCreation")
    print("InDisplay.show[hi[]]")
    print("")
    print("at first example we have:")
    print("a ma_in but for ma_in dosen't show anything we use a InDisplay.show('') empty.")
    print("we create a string with storio [Instr] and with a space we type the var name. and wirh a another space we type a equal mark to compiler knownits the var content with anotger space and type var content in two ' ' to compiler know it is a string. aftervthat we call InDisplay.show to print that with just name of string.")
    print("")
    print("at example 2 we have:")
    print("a empty output ma_in.")
    print("we create a fuction with createFn and type func name after a space. and after another space we type startCreation to start make this fuction. ")
    print("after that we make a var(string)")
    print("And we make returner its with storio [recall] and after a space we type name of var we wanna be returner.")
    print("And finish create fuction with a endCreation method.")
    print("and we type InDisplay.show to print fuction result in screen.")
    print("")
    print("if first time you use XpLevel, for learn compelety go to http://xp.ct.ws/learn.html")
    print("")
    print("I Hope you are learn it.")
    print("")